name: Publish to WinGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/vedantmgoyal2009/winget-pkgs-automation/releaser-action@v1.0.0
        with:
          identifier: rcmaehl.MSEdgeRedirect
          token: ${{ secrets.MSEdgeRedirect_PAT }}
